In [128]:
%load_ext nb_black

<IPython.core.display.Javascript object>

LinAlgError: Last 2 dimensions of the array must be square

In [491]:
y = np.random.randn(3)

In [1047]:
def solve_linear_equations(A, y):
    rank = np.linalg.matrix_rank(A)
    expanded_rank = np.linalg.matrix_rank(np.hstack([A, y[:, None]]))
    if expanded_rank > rank:
        return "NO", None
    if rank < A.shape[1]:
        return "INF", None
    
    u, s, v = np.linalg.svd(A)
    x = np.linalg.inv(v) @ (np.linalg.inv(u) @ y / s)
    return "YES", x
    

In [1050]:
answer, solution = solve_linear_equations(x, y)
print(answer)
if solution is not None:
    print(*solution)

YES
0.26086956521739124 0.04347826086956519 -0.13043478260869537


In [1006]:
if np.linalg.matrix_rank(x[:,:3]) < np.linalg.matrix_rank(x):
    print("NO")
    
if np.linalg.matrix_rank(x) < x.shape[1] - 1:
    print("INF")

xx = np.linalg.eig(np.vstack([x, x[-1, :]]))
for eigenvalue, eigenvector in zip(*xx):
    if abs(eigenvalue) < 1e-5:
        w = np.array(list(map(float, eigenvector/eigenvector[-1])))
        print(eigenvalue, w)


(4.440892098500626e-16+0j) [-0.27415056 -0.40999859 -0.40999859  1.        ]


/tmp/ipykernel_37844/3321589851.py:10: ComplexWarning: Casting complex values to real discards the imaginary part
  w = np.array(list(map(float, eigenvector/eigenvector[-1])))


In [1029]:
np.linalg.inv(vh) @ (np.linalg.inv(u) @ y / s)

array([ 0.26086957,  0.04347826, -0.13043478])

In [1052]:
x[:, -1:]

array([[1],
       [9],
       [3]])

In [1060]:
np.linalg.svd([[1, 2,3],[1,2,3]])

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([5.29150262e+00, 4.44089210e-16]),
 array([[-0.26726124, -0.53452248, -0.80178373],
        [ 0.94491118, -0.30854944, -0.10927077],
        [-0.18898224, -0.78681825,  0.58753958]]))

In [1020]:
n, m = map(int, input().split())
x = []
for _ in range(n):
    x.append(list(map(int, input().split())))
x = np.array(x)

3 3
4 2 1 1
7 8 9 1
9 1 3 2


In [1010]:
x

array([[ 4,  2,  1, -1],
       [ 7,  8,  9, -1],
       [ 9,  1,  3, -2]])

In [743]:
scheduler(1000)

0.0001

In [941]:
edges = np.histogram(x)[1]

In [944]:
(np.array(x) == 1).sum()

0

In [945]:
i = []
for edge in edges:
    i.append((np.array(x) == edge).sum())

In [951]:
x

[4.6,
 7.7,
 6.7,
 6.7,
 6.1,
 6.7,
 5.5,
 7.2,
 4.9,
 7.0,
 7.9,
 6.3,
 5.1,
 7.4,
 5.7,
 5.9,
 6.2,
 4.8,
 5.0,
 5.5,
 6.3,
 6.6,
 6.1,
 7.7,
 5.0,
 4.8,
 6.5,
 4.7,
 6.7,
 5.7,
 4.6,
 5.0,
 6.0,
 6.6,
 4.9,
 5.4,
 5.7,
 6.3,
 5.0,
 4.5,
 4.3,
 4.4,
 6.4,
 6.0,
 5.0,
 5.8,
 5.5,
 6.2,
 4.8,
 6.3,
 5.2,
 4.3,
 5.4,
 5.0,
 6.5,
 4.8,
 7.0,
 4.4,
 5.0,
 5.2,
 4.9,
 7.4,
 5.8,
 5.7,
 4.5,
 5.9,
 5.7,
 6.0,
 5.0,
 5.9,
 5.8,
 6.0,
 6.3,
 5.6,
 6.7,
 7.9,
 6.8,
 5.5,
 6.0,
 5.0,
 6.5,
 5.1,
 5.6,
 5.1,
 5.9,
 6.4,
 5.1,
 7.1,
 6.4,
 5.7,
 5.1,
 6.1,
 4.4,
 6.4,
 7.7,
 6.3,
 5.4,
 6.7,
 6.1,
 6.3,
 4.5,
 4.8,
 5.8,
 7.9,
 6.0,
 6.3,
 4.6,
 5.9,
 7.7,
 6.8,
 5.9,
 6.4,
 5.6,
 4.6,
 4.7,
 5.1,
 5.2,
 6.4,
 6.2,
 4.9,
 5.7,
 5.1,
 5.8,
 6.3,
 5.4,
 4.9,
 4.4,
 6.9,
 6.8,
 6.5,
 5.7,
 6.1,
 5.1,
 6.8,
 6.3,
 7.2,
 5.1,
 5.4,
 5.4,
 7.1,
 4.8,
 5.1,
 5.2,
 6.5,
 6.3,
 6.8,
 5.1,
 5.7,
 6.1,
 5.8]

In [959]:
f = int(input())
print(f"{f:.1f} degrees Fahrenheit is {5/9*(f-32)} degrees Celsius")

123
123.0 degrees Fahrenheit is 50.55555555555556 degrees Celsius


In [949]:
print(*np.histogram(x + [min(x) - 1e-5])[0])

13 22 15 22 18 26 18 5 4 7


In [955]:
x = []
for line in s.splitlines():
    x.append(float(line.split()[0]))

In [954]:
s = """5.0	3.4	1.6	0.4	I.setosa
6.7	3.1	4.7	1.5	I.versicolor
7.7	2.6	6.9	2.3	I.virginica
6.2	3.4	5.4	2.3	I.virginica
5.7	3.0	4.2	1.2	I.versicolor
5.7	2.9	4.2	1.3	I.versicolor
6.2	2.9	4.3	1.3	I.versicolor
6.2	2.2	4.5	1.5	I.versicolor
4.4	3.2	1.3	0.2	I.setosa
5.2	4.1	1.5	0.1	I.setosa
7.2	3.6	6.1	2.5	I.virginica
5.7	2.5	5.0	2.0	I.virginica
5.0	3.3	1.4	0.2	I.setosa
5.0	3.3	1.4	0.2	I.setosa
6.1	3.0	4.6	1.4	I.versicolor
5.4	3.4	1.7	0.2	I.setosa
5.0	3.4	1.5	0.2	I.setosa
5.0	3.0	1.6	0.2	I.setosa
5.5	2.4	3.7	1.0	I.versicolor
4.6	3.4	1.4	0.3	I.setosa
5.2	2.7	3.9	1.4	I.versicolor
5.1	3.7	1.5	0.4	I.setosa
5.6	2.5	3.9	1.1	I.versicolor
6.2	2.8	4.8	1.8	I.virginica
6.6	3.0	4.4	1.4	I.versicolor
5.9	3.0	4.2	1.5	I.versicolor
4.9	3.1	1.5	0.1	I.setosa
6.4	2.8	5.6	2.2	I.virginica
5.0	2.0	3.5	1.0	I.versicolor
5.6	2.5	3.9	1.1	I.versicolor
6.5	3.0	5.8	2.2	I.virginica
6.3	3.3	4.7	1.6	I.versicolor
5.2	3.4	1.4	0.2	I.setosa
6.6	2.9	4.6	1.3	I.versicolor
5.7	3.8	1.7	0.3	I.setosa
6.3	2.8	5.1	1.5	I.virginica
5.4	3.4	1.7	0.2	I.setosa
6.7	3.1	4.4	1.4	I.versicolor
7.1	3.0	5.9	2.1	I.virginica
4.5	2.3	1.3	0.3	I.setosa
5.7	2.8	4.1	1.3	I.versicolor
5.1	3.5	1.4	0.1	I.setosa
6.7	3.3	5.7	2.5	I.virginica
5.5	3.5	1.3	0.2	I.setosa
5.4	3.7	1.5	0.2	I.setosa
5.5	4.2	1.4	0.2	I.setosa
5.1	3.5	1.4	0.1	I.setosa
5.2	3.4	1.4	0.2	I.setosa
6.0	2.9	4.5	1.5	I.versicolor
6.3	2.5	4.9	1.5	I.versicolor
7.7	2.6	6.9	2.3	I.virginica
5.8	2.6	4.0	1.2	I.versicolor
5.0	3.6	1.4	0.2	I.setosa
5.7	2.6	3.5	1.0	I.versicolor
4.6	3.4	1.4	0.3	I.setosa
5.0	3.2	1.2	0.2	I.setosa
5.4	3.4	1.7	0.2	I.setosa
6.8	2.8	4.8	1.4	I.versicolor
5.2	4.1	1.5	0.1	I.setosa
5.4	3.9	1.7	0.4	I.setosa
6.1	2.6	5.6	1.4	I.virginica
6.8	3.2	5.9	2.3	I.virginica
5.8	2.7	3.9	1.2	I.versicolor
5.1	3.3	1.7	0.5	I.setosa
6.0	3.0	4.8	1.8	I.virginica
5.8	2.7	5.1	1.9	I.virginica
5.2	3.5	1.5	0.2	I.setosa
5.5	2.4	3.7	1.0	I.versicolor
6.2	2.2	4.5	1.5	I.versicolor
7.2	3.6	6.1	2.5	I.virginica
6.7	3.3	5.7	2.1	I.virginica
5.2	3.4	1.4	0.2	I.setosa
5.9	3.0	5.1	1.8	I.virginica
5.0	3.5	1.6	0.6	I.setosa
5.4	3.4	1.7	0.2	I.setosa
6.1	2.8	4.0	1.3	I.versicolor
5.8	2.7	3.9	1.2	I.versicolor
6.3	2.5	4.9	1.5	I.versicolor
7.2	3.6	6.1	2.5	I.virginica
5.1	3.3	1.7	0.5	I.setosa
6.7	2.5	5.8	1.8	I.virginica
5.4	3.9	1.3	0.4	I.setosa
4.3	3.0	1.1	0.1	I.setosa
4.4	2.9	1.4	0.2	I.setosa
5.0	3.4	1.5	0.2	I.setosa
6.2	2.2	4.5	1.5	I.versicolor
5.8	2.7	5.1	1.9	I.virginica
6.9	3.1	5.1	2.3	I.virginica
6.7	3.1	4.4	1.4	I.versicolor
6.7	3.1	4.7	1.5	I.versicolor
5.5	2.6	4.4	1.2	I.versicolor
5.0	3.5	1.6	0.6	I.setosa
5.4	3.9	1.3	0.4	I.setosa
7.2	3.0	5.8	1.6	I.virginica
6.3	3.4	5.6	2.4	I.virginica
7.9	3.8	6.4	2.0	I.virginica
5.0	3.5	1.3	0.3	I.setosa
5.7	4.4	1.5	0.4	I.setosa
7.6	3.0	6.6	2.1	I.virginica
6.3	2.5	4.9	1.5	I.versicolor
5.0	3.6	1.4	0.2	I.setosa
5.1	2.5	3.0	1.1	I.versicolor
6.0	3.0	4.8	1.8	I.virginica
4.9	2.5	4.5	1.7	I.virginica
4.6	3.4	1.4	0.3	I.setosa
5.5	4.2	1.4	0.2	I.setosa
5.1	3.4	1.5	0.2	I.setosa
6.3	3.4	5.6	2.4	I.virginica
6.0	3.0	4.8	1.8	I.virginica
6.3	2.9	5.6	1.8	I.virginica
5.0	3.3	1.4	0.2	I.setosa
4.8	3.0	1.4	0.3	I.setosa
4.6	3.4	1.4	0.3	I.setosa
5.5	2.3	4.0	1.3	I.versicolor
6.7	2.5	5.8	1.8	I.virginica
5.7	2.9	4.2	1.3	I.versicolor
4.3	3.0	1.1	0.1	I.setosa
5.5	2.6	4.4	1.2	I.versicolor
5.6	2.9	3.6	1.3	I.versicolor
6.1	2.8	4.0	1.3	I.versicolor
6.5	3.0	5.5	1.8	I.virginica
4.9	3.1	1.5	0.1	I.setosa
5.8	2.8	5.1	2.4	I.virginica
5.2	3.4	1.4	0.2	I.setosa
4.4	3.0	1.3	0.2	I.setosa
5.6	2.9	3.6	1.3	I.versicolor
7.1	3.0	5.9	2.1	I.virginica
4.8	3.0	1.4	0.1	I.setosa
6.5	3.0	5.8	2.2	I.virginica
4.7	3.2	1.3	0.2	I.setosa
6.4	2.9	4.3	1.3	I.versicolor
6.0	3.4	4.5	1.6	I.versicolor
5.8	2.7	3.9	1.2	I.versicolor
5.1	3.4	1.5	0.2	I.setosa
4.6	3.6	1.0	0.2	I.setosa
5.8	2.7	3.9	1.2	I.versicolor
5.2	3.5	1.5	0.2	I.setosa
6.5	3.2	5.1	2.0	I.virginica
5.4	3.9	1.3	0.4	I.setosa
5.6	3.0	4.1	1.3	I.versicolor
6.7	3.0	5.2	2.3	I.virginica
6.5	3.0	5.5	1.8	I.virginica
5.7	2.8	4.5	1.3	I.versicolor
5.4	3.0	4.5	1.5	I.versicolor
5.5	2.5	4.0	1.3	I.versicolor
7.1	3.0	5.9	2.1	I.virginica
6.0	2.2	5.0	1.5	I.virginica
6.1	3.0	4.9	1.8	I.virginica
5.2	4.1	1.5	0.1	I.setosa
4.9	3.6	1.4	0.1	I.setosa
"""

In [ ]:
import subprocess


def wccount(filename):
    out = subprocess.run(['wc', '-l', filename],
                         stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT
                         ).stdout
    return int(out.partition(b' ')[0])



glove_file = "data/glove.6B.300d.txt"
embeddings_dict = {}
with open(glove_file, 'r', encoding='utf-8') as f:
    for line in tqdm(f, "Parsing glove embeddings", total=wccount(glove_file), ncols=100):
        values = line.split()
        token = values[0]
        vector = np.asarray(values[1:], "float32")
        embeddings_dict[token] = vector

embeds = pd.DataFrame(embeddings_dict)
emb_np = embeds.to_numpy().T

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM


tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-ru-en")
model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-ru-en")

def translate(words):
    batch = tokenizer(words, return_tensors="pt", padding=True)
    gen = model.generate(**batch)
    return tokenizer.batch_decode(gen, skip_special_tokens=True)

In [ ]:
from collections import Counter
from scipy import spatial

kdtree = spatial.KDTree(emb_np)

In [ ]:
english_topics = pd.DataFrame()
for col in tqdm(topics, "Translating topic words to english", total=len(topics.columns), position=0, ncols=100):
    words = translate(list(topics[col]))
    words = [''.join([c.lower() for c in word.split()[0] if c.isalpha()]) for word in words]
    english_topics[col] = np.array(words)

In [ ]:
for col, words in tqdm(topics.iteritems(),
                       "Finding names for topics", total=topics.shape[1], position=0, ncols=100):
    words = translate(list(words))
    words = [''.join([c.lower() for c in word.split()[0] if c.isalpha()]) for word in words]
    counter = Counter()
    for word in words:
        if word not in embeds:
            continue
        point = embeds[word].to_numpy()
        distance, indices = kdtree.query(point, range(1, 10))
        for index in indices:
            counter[embeds.columns[index]] += 1
            
    topics.rename({col: counter.most_common()[0][0]}, axis='columns', inplace=True)

In [1]:
import parsl
from parsl.app.app import python_app, bash_app



parsl.load()

In [2]:
@python_app
def slow_hello():
    import time
    time.sleep(5)
    return 'Hello World!'

In [7]:
sh = slow_hello()

In [19]:
print(sh.result() if sh.done() else 'Wait')

Hello World!
