In [1]:
import numpy as np
a = np.arange(12).reshape(3, 4)
b = np.arange(8).reshape(2, 4)
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[0, 1, 2, 3],
        [4, 5, 6, 7]]))

In [39]:
a.shape

(3, 4)

In [92]:
b.reshape(2, 1, 4)

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]]])

In [91]:
b1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]]])

In [67]:
b1 = np.asarray([[b[0]], [b[1]]])

In [68]:
b1.shape

(2, 1, 4)

In [42]:
d = np.empty((2, 3, 4))
d[0] = d[1] = a.copy()
#d[:, :, 0] = d[:, :, 1] = a.copy()

In [ ]:
np.add()

In [63]:
d.shape

(2, 3, 4)

In [75]:
d - b1

array([[[ 0.,  0.,  0.,  0.],
        [ 4.,  4.,  4.,  4.],
        [ 8.,  8.,  8.,  8.]],

       [[-4., -4., -4., -4.],
        [ 0.,  0.,  0.,  0.],
        [ 4.,  4.,  4.,  4.]]])

In [90]:
((d - b1) ** 2).sum(axis=2).argmin(axis=0)

array([0, 1, 1], dtype=int64)

In [59]:
d[0].shape, b[0].shape

((3, 4), (4,))

In [56]:
d - b

ValueError: operands could not be broadcast together with shapes (2,3,4) (2,4) 

In [3]:
c = a.copy()
c.prod?

In [15]:
myf(a[0])

0

In [24]:
(b - a[1]).sum(axis=1)

array([-16,   0])

In [27]:
myf(a[2])

1

In [25]:
def myf(x):
    return ((b - x) ** 2).sum(axis=1).argmin()

In [28]:
np.apply_along_axis(myf, 1, a)

array([0, 1, 1], dtype=int64)

In [30]:
np.mgrid?